services:
  db:
    image: postgres:17.3-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  app:
    build: .
    container_name: app
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/github-runner/emailcopilot-back/Caddyfile:/etc/caddy/Caddyfile

volumes:
  db_data:
