services:
  db:
    image: postgres:17.3-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "3001:3001"

volumes:
  db_data:
