name: Deploy STAGING

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: STAGING
      compose_service: app
    secrets: inherit
